//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTiemChung
    {
        public int idMuiTiem { get; set; }
        public string idTre { get; set; }
        public Nullable<int> idVaccine { get; set; }
        public System.DateTime ngayTiem { get; set; }
        public string tinhTrang { get; set; }
        public Nullable<int> thuTuMuiTiem { get; set; }
        public Nullable<int> idCanBo { get; set; }
    
        public virtual ThongTinCanBo ThongTinCanBo { get; set; }
        public virtual Tre Tre { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
