//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public int idPhieuXuat { get; set; }
        public int idVaccine { get; set; }
        public int soLuongXuat { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
