//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int idPhieuNhap { get; set; }
        public int idVaccine { get; set; }
        public System.DateTime ngaySanXuat { get; set; }
        public System.DateTime ngayHetHan { get; set; }
        public int soLuongNhap { get; set; }
        public Nullable<int> loSanXuat { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
