//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiGiamHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiGiamHo()
        {
            this.Tres = new HashSet<Tre>();
        }
    
        public string idNguoiGiamHo { get; set; }
        public string hoTen { get; set; }
        public string moiQuanHe { get; set; }
        public string SDT { get; set; }
        public string soNha { get; set; }
        public Nullable<int> idPhuongXa { get; set; }
    
        public virtual PhuongXa PhuongXa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tre> Tres { get; set; }
    }
}
