//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongXa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhuongXa()
        {
            this.NguoiGiamHoes = new HashSet<NguoiGiamHo>();
        }
    
        public int idPhuongXa { get; set; }
        public Nullable<int> idQuanHuyen { get; set; }
        public string tenPhuongXa { get; set; }
        public string moTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiGiamHo> NguoiGiamHoes { get; set; }
        public virtual QuanHuyen QuanHuyen { get; set; }
    }
}
