//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.ThongTinCanBoes = new HashSet<ThongTinCanBo>();
        }
    
        public int idTK { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public Nullable<int> idQuyen { get; set; }
    
        public virtual QuyenTruyCap QuyenTruyCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinCanBo> ThongTinCanBoes { get; set; }
    }
}
