//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCanBo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinCanBo()
        {
            this.ChiTietTiemChungs = new HashSet<ChiTietTiemChung>();
            this.PhieuNhaps = new HashSet<PhieuNhap>();
            this.PhieuXuats = new HashSet<PhieuXuat>();
        }
    
        public int idCanBo { get; set; }
        public string hoTen { get; set; }
        public string SDT { get; set; }
        public string eMail { get; set; }
        public string CCCD { get; set; }
        public string diaChi { get; set; }
        public string gioiTinh { get; set; }
        public Nullable<int> idChucVu { get; set; }
        public Nullable<int> idTaiKhoan { get; set; }
        public Nullable<int> idDonVi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTiemChung> ChiTietTiemChungs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual DonVi DonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
