//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom32_QuanLyTiemChung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tre()
        {
            this.ChiTietTiemChungs = new HashSet<ChiTietTiemChung>();
        }
    
        public string idTre { get; set; }
        public string idNguoiGiamHo { get; set; }
        public string hoTen { get; set; }
        public System.DateTime ngaySinh { get; set; }
        public string chieuCao { get; set; }
        public string canNang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTiemChung> ChiTietTiemChungs { get; set; }
        public virtual NguoiGiamHo NguoiGiamHo { get; set; }
    }
}
